# Generated by Django 4.2.7 on 2023-11-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное название')),
                ('short_name', models.CharField(max_length=50, verbose_name='Сокращенное название')),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('enrollment_year', models.IntegerField(verbose_name='Год поступления')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab2.university', verbose_name='Университет')),
            ],
        ),
    ]
