version: '3.8'

services:
  postgresql:
    image: postgres:14.9-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    container_name: 'django-db'
    volumes:
      - ./init-db-postgres:/docker-entrypoint-initdb.d/:ro
    ports:
      - '0.0.0.0:1337:5432/tcp'
    restart: always
